# Generated by Django 3.2.19 on 2023-06-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
